name: Generate Contribution Snake

on:
  push:
    branches: 
      - main
      - release/*
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub contribution snake graph
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake-dark.svg?palette=github-dark
            github-snake-light.svg?palette=github-light
            github-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Upload GitHub contribution graph
        uses: actions/upload-artifact@v3
        with:
          name: github-contribution-graph
          path: .
